### PR TITLE
update supported Go versions to Go 1.21 and 1.22

### PR DESCRIPTION
**Pull request by marten-seemann**

### CODE REVIEW

**Comment by jakubgs** [comment]
Thanks for fixing this. Any plans to create a release that includes this?

**Comment by marten-seemann** [comment]
No, there's no need for a new release.

**Comment by siddarthkay** [comment]
@marten-seemann : When I upgrade status-go to 1.21 I get this error : 

```
/Users/siddarthkumar/gopath/src/github.com/status-im/status-go/vendor/github.com/quic-go
/quic-go/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built 
on Go 1.21 yet. For more details, please see 
https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." 
(untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) 
as int value in variable declaration
```
I could still use master, but would be nice if you'd release it as well.

Thank you :)

**Comment by marten-seemann** [comment]
This is not a qpack error.

**Comment by siddarthkay** [comment]
Yes sorry my bad.

**Pull request merged**
